name: laboratorio_ferreira_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  json_annotation: ^4.6.0
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  mocktail: ^0.3.0
  faker: ^2.0.0

scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs
  gen:watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean:
    - flutter clean
    - flutter pub get
    - flutter pub upgrade
  test: flutter test --verbose
  update:
    - flutter pub get
    - flutter pub upgrade

flutter:
  uses-material-design: true

  assets:
    - .env