name: laboratorio_ferreira_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  email_validator: ^2.1.17
  firebase_core: ^1.21.1
  firebase_crashlytics: ^2.8.9
  flex_color_scheme: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3
  formz: ^0.4.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  json_annotation: ^4.6.0
  jwt_decoder: ^2.0.1
  loggy: ^2.0.1+1
  path: ^1.8.2
  path_provider: ^2.0.11
  sembast: ^3.3.0

dev_dependencies:
  build_runner: ^2.2.0
  faker: ^2.0.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  source_gen: ^1.2.2

flutter_native_splash:
  image: assets/laboratorioferreira_logo_sem_fundo.png
  color: 'CCD5AE'
  android_12:
    image: assets/laboratorioferreira_logo_sem_fundo.png
    color: 'CCD5AE'
  android: true
  ios: true
  web: false
  fullscreen: true

scripts:
  create_splash: flutter pub run flutter_native_splash:create
  gen: flutter pub run build_runner build --delete-conflicting-outputs
  gen_watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean:
    - flutter clean
    - flutter pub get
    - flutter pub upgrade
    - $gen_watch
  test: flutter test --verbose
  update:
    - flutter pub get
    - flutter pub upgrade
  db_analyze: flutter pub run drift_dev analyze

flutter:
  uses-material-design: true
  assets:
    - assets/
