name: laboratorio_ferreira_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  collection: ^1.17.0
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_performance: ^0.9.0+7
  flex_seed_scheme: ^1.1.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_riverpod: ^2.1.1
  form_builder_validators: ^8.4.0
  freezed_annotation: ^2.2.0
  go_router: ^5.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.1
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1
  loggy: ^2.0.3
  mask: ^1.0.4
  path: ^1.8.2
  path_provider: ^2.0.11
  pretty_dio_logger: ^1.1.1
  riverpod_annotation: ^1.0.6
  sembast: ^3.3.1
  very_good_infinite_list: ^0.7.0

dev_dependencies:
  build_runner: ^2.3.2
  faker: ^2.1.0
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  riverpod_generator: ^1.0.6

flutter_native_splash:
  image: assets/laboratorioferreira_logo_sem_fundo.png
  color: 'CCD5AE'
  android_12:
    image: assets/laboratorioferreira_logo_sem_fundo.png
    color: 'CCD5AE'
  android: true
  ios: true
  web: false
  fullscreen: true

flutter_gen:
  output: lib/generated
  colors:
    inputs:
      - assets/colors/colors.xml

scripts:
  create_splash: flutter pub run flutter_native_splash:create
  gen: flutter pub run build_runner build --delete-conflicting-outputs
  gen_watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean:
    - flutter clean
    - flutter pub get
    - flutter pub upgrade
    - derry gen
  test: flutter test --coverage
  update:
    - flutter pub get
    - flutter pub upgrade

flutter:
  uses-material-design: true
  assets:
    - assets/images/
