name: laboratorio_ferreira_mobile
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  bloc_concurrency: ^0.2.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_loggy: ^2.0.1
  flutter_loggy_dio: ^2.0.0+3
  formz: ^0.4.1
  freezed_annotation: ^2.1.0
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.6.0
  jwt_decoder: ^2.0.1
  loggy: ^2.0.1+1
  path: ^1.8.1
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.2.0
  faker: ^2.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  source_gen: ^1.2.2

scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs
  gen:watch: flutter pub run build_runner watch --delete-conflicting-outputs
  clean:
    - flutter clean
    - flutter pub get
    - flutter pub upgrade
    - $gen
  test: flutter test --verbose
  update:
    - flutter pub get
    - flutter pub upgrade

flutter:
  uses-material-design: true
  assets:
    - assets/
