name: Release APK

on:
  push:
    tags:
      - '*'
    branches-ignore:
      - '!main'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build apk
        run: flutter build apk --split-per-abi --obfuscate --split-debug-info --release --dart-define=API_URL=${{secrets.API_URL}}
      - name: Release apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/apk/release/*.apk
          token: ${{secrets.GITHUB_TOKEN}}
          commit: main
          tag: v1.0.${{github.run_number}}